SELECT DATE_ADD(time, INTERVAL 14 DAY) AS time_predic, activeIKWH
FROM Gefen_LP_counters_30minutes
WHERE DAYOFWEEK(`time`) IN (5,6,7)
AND `time` >= DATE_SUB(DATE_SUB(CURDATE(), INTERVAL (DAYOFWEEK(CURDATE()) - 1) DAY), INTERVAL 1 WEEK) -- Last week's data
AND `time` < DATE_SUB(DATE_SUB(CURDATE(), INTERVAL (DAYOFWEEK(CURDATE()) - 1) DAY), INTERVAL 0 WEEK)

UNION ALL

SELECT DATE_ADD(time, INTERVAL 21 DAY) AS time_predic, activeIKWH
FROM Gefen_LP_counters_30minutes
WHERE DAYOFWEEK(`time`) IN (1,2,3,4,5,6,7)
AND `time` >= DATE_SUB(DATE_SUB(CURDATE(), INTERVAL (DAYOFWEEK(CURDATE()) - 1) DAY), INTERVAL 1 WEEK) -- Last week's data
AND `time` < DATE_SUB(DATE_SUB(CURDATE(), INTERVAL (DAYOFWEEK(CURDATE()) - 1) DAY), INTERVAL 0 WEEK)